import { expect, test } from '@playwright/test'
import { mkdir, writeFile } from 'node:fs/promises'
import { dirname } from 'node:path'
import { randomUUID } from 'node:crypto'

test('complete shop workflow survives refresh and login', async ({ page }, testInfo) => {
  test.setTimeout(90000)
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  const email = `e2e-${randomUUID()}@example.invalid`
  const password = `Test-only-${randomUUID()}`
  await page.goto('/#/register')
  await page.getByLabel('Your name').fill('Shop Owner')
  await page.getByLabel('Business name').fill('Everyday Store')
  await page.getByLabel('Email address').fill(email)
  await page.getByLabel('Password', { exact: false }).fill(password)
  const registration = page.waitForResponse(response => response.url().endsWith('/api/auth/register'))
  await page.getByRole('button', { name: 'Create account', exact: true }).click()
  const response = await registration
  expect(response.status()).toBe(201)
  const account = await response.json()
  const fixturePath = testInfo.outputPath('fixture-user.json')
  await mkdir(dirname(fixturePath), { recursive: true })
  await writeFile(fixturePath, JSON.stringify({ userId: account.user.id })) // no token/password persisted
  await expect(page.getByRole('heading', { name: 'Hello, Shop' })).toBeVisible()

  async function createProduct(name, unit, stock, minimum, price = '') {
    await page.goto('/#/products/new')
    await page.getByLabel('Product name').fill(name)
    await page.getByLabel('Category').fill('Grocery')
    await page.getByLabel('Unit', { exact: false }).selectOption(unit)
    await page.getByLabel('Initial stock').fill(String(stock))
    await page.getByLabel('Minimum stock', { exact: false }).fill(String(minimum))
    await page.getByLabel('Price (optional)').fill(price)
    await page.getByRole('button', { name: 'Create product', exact: true }).click()
    await expect(page.getByRole('heading', { name, exact: true })).toBeVisible()
    return page.url().split('#')[1]
  }
  const ricePath = await createProduct('Rice', 'BAGS', 50, 10, '1200')
  await expect(page.getByTestId('product-stock')).toHaveText('50 bags')
  await page.getByRole('link', { name: '+ Add stock', exact: true }).click()
  await page.getByLabel('Quantity (bags)').fill('20')
  await page.getByRole('button', { name: 'Confirm add stock' }).click()
  await expect(page.getByRole('status')).toContainText('Rice now has 70 bags')
  await page.getByRole('link', { name: 'Back to inventory' }).click()
  await expect(page.getByTestId('product-stock')).toHaveText('70 bags')
  await page.getByRole('link', { name: '− Remove stock', exact: true }).click()
  await page.getByLabel('Quantity (bags)').fill('5')
  await page.getByRole('button', { name: 'Confirm remove stock' }).click()
  await expect(page.getByRole('status')).toContainText('Rice now has 65 bags')
  await page.getByLabel('Quantity (bags)').fill('100')
  await page.getByRole('button', { name: 'Confirm remove stock' }).click()
  await expect(page.getByRole('alert')).toContainText('Only 65 bags available')
  await page.goto('/#' + ricePath)
  await page.reload()
  await expect(page.getByTestId('product-stock')).toHaveText('65 bags')
  await createProduct('Sugar', 'KG', 4, 5)
  const biscuitsPath = await createProduct('Biscuits', 'BOXES', 0, 5)
  await page.goto('/#/alerts')
  await expect(page.locator('article').filter({ hasText: 'Sugar' })).toContainText('Low stock')
  await expect(page.locator('article').filter({ hasText: 'Sugar' })).toContainText('6 kg')
  await expect(page.locator('article').filter({ hasText: 'Biscuits' })).toContainText('Out of stock')
  await page.goto('/#/dashboard')
  await expect(page.getByTestId('stat-Products')).toHaveText('3')
  await expect(page.getByTestId('stat-Low stock')).toHaveText('1')
  await expect(page.getByTestId('stat-Out of stock')).toHaveText('1')
  await expect(page.getByTestId('stat-Today’s transactions')).toHaveText('4')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('dashboard.png'), fullPage: true })
  await page.goto('/#/transactions')
  await expect(page.getByText('+20 bags', { exact: true })).toBeVisible()
  await expect(page.getByText('−5 bags', { exact: true })).toBeVisible()
  await expect(page.getByText('+50 bags', { exact: true })).toBeVisible()
  await page.goto('/#/inventory')
  await page.getByLabel('Search products').fill('rice')
  await expect(page.locator('article')).toHaveCount(1)
  await page.getByRole('link', { name: 'Rice', exact: true }).click()
  await page.getByRole('link', { name: 'Edit product' }).click()
  await page.getByLabel('Category').fill('Staples')
  await page.getByLabel('Price (optional)').fill('1250')
  await page.getByRole('button', { name: 'Save changes' }).click()
  await expect(page.getByTestId('product-stock')).toHaveText('65 bags')
  await expect(page.getByText('Staples', { exact: true })).toBeVisible()
  await page.goto('/#/settings')
  await page.getByLabel('Business name').fill('Everyday Store Updated')
  await page.getByLabel('Preferred language', { exact: false }).selectOption('te')
  await page.getByRole('button', { name: 'Save profile' }).click()
  await expect(page.getByRole('status')).toHaveText('Your profile has been saved.')
  await page.reload()
  await expect(page.getByLabel('Business name')).toHaveValue('Everyday Store Updated')
  await expect(page.getByLabel('Preferred language', { exact: false })).toHaveValue('te')
  await page.goto('/#/voice')
  await expect(page.getByRole('button', { name: 'Tap to Speak', exact: true })).toBeVisible()
  await expect(page.getByRole('link', { name: '+ Add stock manually' })).toBeVisible()
  await page.goto('/#' + biscuitsPath)
  await page.getByRole('button', { name: 'Archive product', exact: true }).click()
  await page.getByRole('button', { name: 'Confirm archive' }).click()
  await expect(page.getByRole('heading', { name: 'Inventory', exact: true })).toBeVisible()
  await expect(page.locator('article').filter({ hasText: 'Biscuits' })).toHaveCount(0)
  if (page.viewportSize().width < 1024) await page.getByText('Menu', { exact: true }).click()
  await page.getByRole('button', { name: 'Log out', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Welcome back' })).toBeVisible()
  expect(await page.evaluate(() => sessionStorage.getItem('voicestock.session'))).toBeNull()
  await page.getByLabel('Email address').fill(email)
  await page.getByLabel('Password').fill(password)
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Hello, Shop' })).toBeVisible()
  await page.goto('/#' + ricePath)
  await expect(page.getByTestId('product-stock')).toHaveText('65 bags')
  expect(errors).toEqual([])
})

