import { BusinessSummary } from './ActionCenter.jsx'
import { useData } from '../services/useData.js'
import { Empty, Heading, Icon, LinkButton, LoadState, TransactionList } from '../components/UI.jsx'

export default function Dashboard({ user }) {
  const resource = useData(`/dashboard?timeZone=${encodeURIComponent(Intl.DateTimeFormat().resolvedOptions().timeZone)}`)
  if (!resource.data) return <LoadState {...resource} />
  const d = resource.data
  const cards = [['Products', d.totalProducts, '/inventory', 'box', 'bg-[#eef3e8] text-[#56763c]'], ['Low stock', d.lowStock, '/alerts', 'bell', 'bg-amber-50 text-amber-700'], ['Out of stock', d.outOfStock, '/alerts', 'box', 'bg-red-50 text-red-700'], ["Today’s transactions", d.todaysTransactions, '/transactions', 'history', 'bg-blue-50 text-blue-700']]
  return <><Heading title={`Hello, ${user.name.split(' ')[0]}`} description={`Here’s what’s happening at ${user.businessName}.`} /><section className="mb-7 flex flex-wrap items-center justify-between gap-6 rounded-2xl bg-[#173f35] p-6 text-white sm:p-8"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-[#d8efad]">VoiceStock</p><h2 className="mt-3 text-2xl font-semibold">Manage inventory as naturally as you speak — and know what to do next.</h2><p className="mt-3 max-w-lg text-sm leading-6 text-white/65">Try saying: “Add 10 bags of rice” · “Rice 5 bags add cheyyi” · “How much rice do I have?”</p></div><a href="#/voice" className="flex min-h-24 shrink-0 items-center gap-4 rounded-2xl bg-[#d8efad] px-6 py-5 text-[#173f35] hover:bg-[#e5f7c8]"><Icon name="mic" className="h-9 w-9" /><span className="font-bold">Voice assistant<span className="mt-1 block text-xs font-normal">Speak or type a command</span></span></a></section><div className="mb-7 grid grid-cols-2 gap-3 xl:grid-cols-4">{cards.map(([label, number, to, icon, style]) => <a href={`#${to}`} key={label} className="panel p-4 sm:p-5"><span className={`mb-4 inline-flex rounded-lg p-2 ${style}`}><Icon name={icon} /></span><p className="text-3xl font-semibold tracking-tight tabular-nums" data-testid={`stat-${label}`}>{number}</p><p className="mt-2 text-xs font-medium text-slate-500 sm:text-sm">{label}</p></a>)}</div><BusinessSummary /><section className="mb-7"><h2 className="mb-3 text-sm font-semibold text-slate-500">QUICK ACTIONS</h2><div className="grid grid-cols-1 gap-3 sm:grid-cols-3"><LinkButton to="/products/new"><Icon name="plus" />Add product</LinkButton><LinkButton to="/stock?mode=add" secondary><Icon name="plus" />Add stock</LinkButton><LinkButton to="/stock?mode=remove" secondary><Icon name="minus" />Remove stock</LinkButton></div></section><section className="panel p-5 sm:p-6"><div className="mb-3 flex items-center justify-between"><h2 className="text-lg font-semibold">Recent activity</h2><a href="#/transactions" className="text-sm font-semibold text-[#55763e] hover:underline">View all</a></div>{d.recentTransactions.length ? <TransactionList items={d.recentTransactions} /> : <Empty title="Your first update starts here" text="Add a product with opening stock to start your inventory history."><LinkButton to="/products/new">Add your first product</LinkButton></Empty>}</section></>
}


