import { useState } from 'react'
import { useData } from '../services/useData.js'
import { Empty, Heading, Icon, LinkButton, LoadState, Pagination, Status } from '../components/UI.jsx'
import { quantity, unitLabel } from '../services/format.js'

export default function Inventory({ alerts = false }) {
  const [search, setSearch] = useState('')
  const [page, setPage] = useState(0)
  const resource = useData(alerts ? `/inventory/low-stock?page=${page}` : `/products?search=${encodeURIComponent(search)}&page=${page}`)
  return <><Heading title={alerts ? 'Stock alerts' : 'Inventory'} description={alerts ? 'See what needs your attention and how much to reorder.' : 'Your products and current stock, all in one place.'}><LinkButton to="/products/new"><Icon name="plus" />Add product</LinkButton></Heading>{!alerts && <label className="mb-5 block"><span className="sr-only">Search products</span><input className="input max-w-lg" placeholder="Search by product or category…" value={search} onChange={e => { setSearch(e.target.value); setPage(0) }} /></label>}{resource.loading || resource.error ? <LoadState {...resource} /> : !resource.data?.items.length ? <Empty title={alerts ? 'All stocked up' : search ? 'No matching products' : 'Add your first product'} text={alerts ? 'No products are low or out of stock.' : search ? 'Try another product name or category.' : 'Start with the items you sell. Your stock will be saved securely.'}>{!search && !alerts && <LinkButton to="/products/new">Add product</LinkButton>}</Empty> : <><p className="mb-3 text-sm text-slate-500">{resource.data.totalElements} {alerts ? 'products need attention' : 'products'}</p><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{resource.data.items.map(p => <article key={p.id} className="panel flex flex-col p-5"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><a href={`#/products/${p.id}`} className="text-lg font-semibold break-words hover:underline">{p.name}</a><p className="mt-1 text-xs text-slate-500">{p.category}</p></div><Status value={p.status} /></div><p className="mt-6 text-3xl font-semibold tabular-nums">{quantity(p.currentStock)} <span className="text-sm font-normal text-slate-500">{unitLabel(p.unit)}</span></p><p className="mt-2 text-xs text-slate-500">Minimum: {quantity(p.minimumStock)} {unitLabel(p.unit)}</p>{alerts && <p className="mt-4 rounded-lg bg-[#f2f5ec] p-3 text-sm">Suggested reorder: <strong>{quantity(p.reorderQuantity)} {unitLabel(p.unit)}</strong></p>}<div className="mt-5 grid grid-cols-2 gap-2"><LinkButton to={`/stock?mode=add&productId=${p.id}`} secondary><Icon name="plus" />Add</LinkButton><LinkButton to={`/stock?mode=remove&productId=${p.id}`} secondary><Icon name="minus" />Remove</LinkButton></div></article>)}</div><Pagination data={resource.data} onPage={setPage} /></>}</>
}
